BOOLEAN_OPTION_TYPE = ['false', 'true']

# Extracted from the documentation of clang-format version 13
# https://releases.llvm.org/13.0.0/tools/clang/docs/ClangFormatStyleOptions.html
ALL_TUNEABLE_OPTIONS = {
    'AccessModifierOffset': ['0', '-1', '-2', '-3', '-4'],
    'AlignAfterOpenBracket': ['DontAlign', 'Align', 'AlwaysBreak'],
    'AlignArrayOfStructures': ['None', 'Left', 'Right'],
    'AlignConsecutiveAssignments': ['None', 'Consecutive', 'AcrossEmptyLines', 'AcrossComments', 'AcrossEmptyLinesAndComments'],
    'AlignConsecutiveBitFields': ['None', 'Consecutive', 'AcrossEmptyLines', 'AcrossComments', 'AcrossEmptyLinesAndComments'],
    'AlignConsecutiveDeclarations': ['None', 'Consecutive', 'AcrossEmptyLines', 'AcrossComments', 'AcrossEmptyLinesAndComments'],
    'AlignConsecutiveMacros': ['None', 'Consecutive', 'AcrossEmptyLines', 'AcrossComments', 'AcrossEmptyLinesAndComments'],
    'AlignEscapedNewlines': ['DontAlign', 'Left', 'Right'],
    'AlignOperands': ['DontAlign', 'Align', 'AlignAfterOperator'],
    'AlignTrailingComments': BOOLEAN_OPTION_TYPE,
    'AllowAllArgumentsOnNextLine': BOOLEAN_OPTION_TYPE,
    'AllowAllConstructorInitializersOnNextLine': BOOLEAN_OPTION_TYPE,
    'AllowAllParametersOfDeclarationOnNextLine': BOOLEAN_OPTION_TYPE,
    'AllowShortBlocksOnASingleLine': ['Never', 'Empty', 'Always'],
    'AllowShortCaseLabelsOnASingleLine': BOOLEAN_OPTION_TYPE,
    'AllowShortEnumsOnASingleLine': BOOLEAN_OPTION_TYPE,
    'AllowShortFunctionsOnASingleLine': ['None', 'InlineOnly', 'Empty', 'Inline', 'All'],
    'AllowShortIfStatementsOnASingleLine': ['Never', 'WithoutElse', 'OnlyFirstIf', 'AllIfsAndElse'],
    'AllowShortLambdasOnASingleLine': ['None', 'Empty', 'Inline', 'All'],
    'AllowShortLoopsOnASingleLine': BOOLEAN_OPTION_TYPE,
    'AlwaysBreakAfterDefinitionReturnType': ['None', 'All', 'TopLevel'],
    'AlwaysBreakAfterReturnType': ['None', 'All', 'TopLevel', 'AllDefinitions', 'TopLevelDefinitions'],
    'AlwaysBreakBeforeMultilineStrings': BOOLEAN_OPTION_TYPE,
    'AlwaysBreakTemplateDeclarations': ['No', 'MultiLine', 'Yes'],
    'BinPackArguments': BOOLEAN_OPTION_TYPE,
    'BinPackParameters': BOOLEAN_OPTION_TYPE,
    'BitFieldColonSpacing': ['Both', 'None', 'Before', 'After'],
    'BraceWrapping:AfterCaseLabel': BOOLEAN_OPTION_TYPE,
    'BraceWrapping:AfterClass': BOOLEAN_OPTION_TYPE,
    'BraceWrapping:AfterControlStatement': ['Never', 'MultiLine', 'Always'],
    'BraceWrapping:AfterEnum': BOOLEAN_OPTION_TYPE,
    'BraceWrapping:AfterFunction': BOOLEAN_OPTION_TYPE,
    'BraceWrapping:AfterNamespace': BOOLEAN_OPTION_TYPE,
    'BraceWrapping:AfterStruct': BOOLEAN_OPTION_TYPE,
    'BraceWrapping:AfterUnion': BOOLEAN_OPTION_TYPE,
    'BraceWrapping:BeforeCatch': BOOLEAN_OPTION_TYPE,
    'BraceWrapping:BeforeElse': BOOLEAN_OPTION_TYPE,
    'BraceWrapping:BeforeLambdaBody': BOOLEAN_OPTION_TYPE,
    'BraceWrapping:BeforeWhile': BOOLEAN_OPTION_TYPE,
    'BraceWrapping:IndentBraces': BOOLEAN_OPTION_TYPE,
    'BraceWrapping:SplitEmptyFunction': BOOLEAN_OPTION_TYPE,
    'BraceWrapping:SplitEmptyRecord': BOOLEAN_OPTION_TYPE,
    'BraceWrapping:SplitEmptyNamespace': BOOLEAN_OPTION_TYPE,
    'BreakBeforeBinaryOperators': ['None', 'NonAssignment', 'All'],
    'BreakBeforeConceptDeclarations': BOOLEAN_OPTION_TYPE,
    'BreakBeforeInheritanceComma': BOOLEAN_OPTION_TYPE,
    'BreakBeforeTernaryOperators': BOOLEAN_OPTION_TYPE,
    'BreakConstructorInitializersBeforeComma': BOOLEAN_OPTION_TYPE,
    'BreakConstructorInitializers': ['BeforeColon', 'BeforeComma', 'AfterColon'],
    'BreakInheritanceList': ['BeforeColon', 'BeforeComma', 'AfterColon', 'AfterComma'],
    'BreakStringLiterals': BOOLEAN_OPTION_TYPE,
    'ColumnLimit': ['78', '80', '90', '100', '120', '0'],
    'CompactNamespaces': BOOLEAN_OPTION_TYPE,
    'ConstructorInitializerAllOnOneLineOrOnePerLine': BOOLEAN_OPTION_TYPE,
    'ConstructorInitializerIndentWidth': ['0', '2', '3', '4', '6', '8'],
    'ContinuationIndentWidth': ['0', '2', '3', '4', '6', '8'],
    'Cpp11BracedListStyle': BOOLEAN_OPTION_TYPE,
    'EmptyLineAfterAccessModifier': ['Leave', 'Never', 'Always'],
    'EmptyLineBeforeAccessModifier': ['Leave', 'Never', 'LogicalBlock', 'Always'],
    'FixNamespaceComments': BOOLEAN_OPTION_TYPE,
    'IncludeBlocks': ['Preserve', 'Merge', 'Regroup'],
    'IndentAccessModifiers': BOOLEAN_OPTION_TYPE,
    'IndentCaseBlocks': BOOLEAN_OPTION_TYPE,
    'IndentCaseLabels': BOOLEAN_OPTION_TYPE,
    'IndentExternBlock': ['NoIndent', 'Indent'],
    'IndentGotoLabels': BOOLEAN_OPTION_TYPE,
    'IndentPPDirectives': ['None', 'AfterHash', 'BeforeHash'],
    'IndentRequires': BOOLEAN_OPTION_TYPE,
    'IndentWidth': ['2', '3', '4', '8'],
    'IndentWrappedFunctionNames': BOOLEAN_OPTION_TYPE,
    'InsertTrailingCommas': ['None', 'Wrapped'],
    'KeepEmptyLinesAtTheStartOfBlocks': BOOLEAN_OPTION_TYPE,
    'LambdaBodyIndentation': ['Signature', 'OuterScope'],
    'MaxEmptyLinesToKeep': ['0', '1', '2', '3'],
    'NamespaceIndentation': ['None', 'Inner', 'All'],
    'PenaltyBreakAssignment': ['2', '100', '1000'],
    'PenaltyBreakBeforeFirstCallParameter': ['1', '19', '100'],
    'PenaltyBreakComment': ['300'],
    'PenaltyBreakFirstLessLess': ['120'],
    'PenaltyBreakString': ['1000'],
    'PenaltyBreakTemplateDeclaration': ['10'],
    'PenaltyExcessCharacter': ['100', '1000000'],
    'PenaltyReturnTypeOnItsOwnLine': ['60', '200', '1000'],
    'PenaltyIndentedWhitespace': ['0', '1'],
    'PointerAlignment': ['Left', 'Right', 'Middle'],
    'ReferenceAlignment': ['Pointer', 'Left', 'Right', 'Middle'],
    'ReflowComments': BOOLEAN_OPTION_TYPE,
    'ShortNamespaceLines': ['0', '1'],
    'SortIncludes': ['Never', 'CaseSensitive', 'CaseInsensitive'],
    'SortUsingDeclarations': BOOLEAN_OPTION_TYPE,
    'SpaceAfterCStyleCast': BOOLEAN_OPTION_TYPE,
    'SpaceAfterLogicalNot': BOOLEAN_OPTION_TYPE,
    'SpaceAfterTemplateKeyword': BOOLEAN_OPTION_TYPE,
    'SpaceAroundPointerQualifiers': ['Default', 'Before', 'After', 'Both'],
    'SpaceBeforeAssignmentOperators': BOOLEAN_OPTION_TYPE,
    'SpaceBeforeCaseColon': BOOLEAN_OPTION_TYPE,
    'SpaceBeforeCpp11BracedList': BOOLEAN_OPTION_TYPE,
    'SpaceBeforeCtorInitializerColon': BOOLEAN_OPTION_TYPE,
    'SpaceBeforeInheritanceColon': BOOLEAN_OPTION_TYPE,
    'SpaceBeforeParens': ['Never', 'ControlStatements', 'ControlStatementsExceptControlMacros', 'NonEmptyParentheses', 'Always'],
    'SpaceBeforeRangeBasedForLoopColon': BOOLEAN_OPTION_TYPE,
    'SpaceInEmptyBlock': BOOLEAN_OPTION_TYPE,
    'SpaceInEmptyParentheses': BOOLEAN_OPTION_TYPE,
    'SpacesBeforeTrailingComments': ['0', '1'],
    'SpacesInAngles': ['Leave', 'Never', 'Always'],
    'SpacesInCStyleCastParentheses': BOOLEAN_OPTION_TYPE,
    'SpacesInConditionalStatement': BOOLEAN_OPTION_TYPE,
    'SpacesInContainerLiterals': BOOLEAN_OPTION_TYPE,
    'SpacesInLineCommentPrefix:Minimum': ['0', '1'],
    'SpacesInLineCommentPrefix:Maximum': ['0', '1', '-1'],
    'SpacesInParentheses': BOOLEAN_OPTION_TYPE,
    'SpacesInSquareBrackets': BOOLEAN_OPTION_TYPE,
    'SpaceBeforeSquareBrackets': BOOLEAN_OPTION_TYPE,
    'Standard': ['c++03', 'c++11', 'c++14', 'c++17', 'c++20', 'Latest'],
    'UseTab': ['Never', 'ForIndentation', 'ForContinuationAndIndentation', 'AlignWithSpaces', 'Always'],
}

PRIORITY_OPTIONS = ['IndentWidth', 'UseTab', 'SortIncludes', 'IncludeBlocks']
